### ISSUE TITLE
TransferNFT failure 

### ISSUE THREAD

**Issue by fallanic** [tokenbound/sdk#26]
Hi there,

I was playing around with the sdk (great job BTW), but I'm hitting a wall right now, getting an error from Viem.
For context, I am trying to send an NFT (on Polygon Mumbai) from a Sepolia TBA to another Sepolia TBA (let's call them TBA 1 and TBA 2).
When checking with Alchemy api, Alchemy can confirms TBA 1 owns the Mumbai NFT 👍 , despite being a Sepolia TBA.

```
{"ownedNfts":[{"contract":{"address":"0x642070e041326d3aff020f0acbadc96211979a2b","name":"TestTruckNFT","symbol":"TTNFT","totalSupply":"14","tokenType":"ERC721","openSea":{"lastIngestedAt":"2023-09-13T19:43:42.000Z"},"contractDeployer":"0xe1360c82357e5c0bbbf2eafe859aa0ab6d494eed","deployedBlockNumber":39194749},"tokenId":"4","tokenType":"ERC721","title":"Truck #4","description":"This truck will bring you wealth","timeLastUpdated":"2023-09-19T21:24:10.385Z","rawMetadata":{"name":"Truck #4","description":"This truck will bring you wealth","image":"ipfs://bafybeiecreihqxsd6tur7cjcbmb6kixwalxyq6ncfqexjctwf3bangk4he/2.png","attributes":[{"value":"blue","trait_type":"Driver's cab"}]},"tokenUri":{"gateway":"https://alchemy.mypinata.cloud/ipfs/bafybeiczazqgh55rsxbl2povopejkdunjhnfft4g6eq2tcrjaamcizv5bq/4.json","raw":"ipfs://bafybeiczazqgh55rsxbl2povopejkdunjhnfft4g6eq2tcrjaamcizv5bq/4.json"},"media":[{"gateway":"https://nft-cdn.alchemy.com/matic-mumbai/bf08e4b8e6e6ac3177c4c706fe72b35e","thumbnail":"https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/matic-mumbai/bf08e4b8e6e6ac3177c4c706fe72b35e","raw":"ipfs://bafybeiecreihqxsd6tur7cjcbmb6kixwalxyq6ncfqexjctwf3bangk4he/2.png","format":"png","bytes":322595}],"balance":1}],"totalCount":1,"blockHash":"0x6d1790c23d6fb30fda06516fd284fc201c3bae87afda8cc2c9ec6435f1c0ca04"}
```

I am calling `tokenboundClient.transferNFT` like this

```
const tokenboundClient = new TokenboundClient({
    walletClient,
    chainId: polygonMumbai.id,
  });
// context: TBA 1 contains an NFT on Polygon Mumbai (the token 4 of 0x642070e041326d3aff020f0acbadc96211979a2b)
tokenboundClient.transferNFT({
    account: "0x78742d6d40ceca62f6ED8e41DE64F6A5e100dFBb", //  address of TBA 1
    tokenType: "ERC721",
    tokenContract: "0x642070e041326d3aff020f0acbadc96211979a2b", // address of the NFT contract
    tokenId: "4",
    recipientAddress: "0x745F0E3748DbCD3CEE5117F0971a30aE8Bb7275D", // address of TBA 2
  });
```
and as a response I get

```
ContractFunctionExecutionError: The contract function "executeCall" returned no data ("0x").

This could be due to any of the following:
  - The contract does not have the function "executeCall",
  - The parameters passed to the contract function may be invalid, or
  - The address is not a contract.
 
Contract Call:
  address:   0x78742d6d40ceca62f6ED8e41DE64F6A5e100dFBb
  function:  executeCall(address to, uint256 value, bytes data)
  args:                 (0x642070e041326d3aff020f0acbadc96211979a2b, 0, 0x4284...redacted...00000000000000000000000000000000000000000004)
  sender:    0x...redacted...this-is-my-metamask-wallet-address...
```

which makes sense, because `0x78742d6d40ceca62f6ED8e41DE64F6A5e100dFBb` is not a contract address, it's a TBA address.
Did I get the parameters wrong?

Thanks in advance!

**Comment by bjfresh** [comment]
Communicated via Slack, but posting here for reference before closing:

This is most assuredly a cross-chain execution issue. TBAs will be able to do this sort of thing, but at the moment it's not built into the SDK.

The TBA address

`0x78742d6d40ceca62f6ED8e41DE64F6A5e100dFBb`

is a contract address, deployed as a proxied smart contract wallet.

The issue here is that when the chainId is specified as `polygonMumbai.id` functionality is scoped to the mumbai chain. 

So when tokenContract + tokenId are specified in the transfer function, there's nothing to indicate that the contract address lives on Sepolia vs. Mumbai.

The V3 implementation of 6551 will have much more robust support for cross-chain execution in this manner. Implementation-wise, this is an added layer of complexity and we'll have to be thoughtful about how it's exposed to users.
