### ISSUE TITLE
base-sepolia support

### ISSUE THREAD

**Issue by SweetmanTech** [tokenbound/sdk#68]
Can you please expand the Tokenbound SDK to support `baseSepoli`?
- chainId: `84532`

example where I am using `viem`
```
const walletClient: WalletClient = createWalletClient({
	chain: baseSepolia,
	account: address as `0x${string}`,
	transport: http(),
})
```

getting the following error
<img width="463" alt="Screenshot 2024-04-10 at 10 27 55 PM" src="https://github.com/tokenbound/sdk/assets/23249402/7b990cd2-8ab9-40b2-bba9-550ade927f85">

**Comment by ikeorizu** [comment]
This is needed, can't test on Base

**Comment by bjfresh** [comment]
@SweetmanTech in the works. For now, though, you should be able to pass baseSepolia as a custom chain by passing chain as param instead of chainId when instantiating the TokenboundClient, like so: https://docs.tokenbound.org/sdk/methods#custom-chain 

```
import { zora } from 'viem/chains'
const tokenboundClient = new TokenboundClient({ walletClient, chain: zora })
```

We consciously removed the viem/chains from the package except for deployed chains a few months back because it contributed >40% of the bundle size of the SDK. As new chains get 6551 deployments we've been plugging them in. 

I'm working on getting a new build together ASAP now that there's a Base Sepolia deployment.

**Comment by bjfresh** [comment]
https://github.com/tokenbound/sdk/releases/tag/v0.5.2
